tushare:
    token: "2876ea85cb005fb5fa17c809a98174f2d5aae8b1f830110a5ead6211"

api_profile:
    daily:
        expire_days: 1
        incremental_update: True
    trade_cal:
        expire_days: 1
    stock_basic:
        expire_days: 1
    listed_shares:
        expire_days: 1
    stk_limits:
        expire_days: 1
        incremental_update: True
    limit_list_ths:
        expire_days: 1
    limit_list_d:
        expire_days: 1
    default:
        expire_days: 5
        incremental_update: False

field_types:
    # daily
    ts_code: "str"
    trade_date: "str"
    open: "float64"
    high: "float64"
    low: "float64"
    close: "float64"
    pre_close: "float64"
    change: "float64"
    pct_chg: "float64"
    vol: "float64"
    amount: "float64"

    # trade_cal
    exchange: "str"
    cal_date: "str"
    is_open: "str"
    pretrade_date: "str"

    # stock_basic
    symbol: "str"
    name: "str"
    area: "str"
    industry: "str"
    fullname: "str"
    enname: "str"
    cnspell: "str"
    market: "str"
    curr_type: "str"
    list_date: "str"
    delist_date: "str"
    list_status: "str"
    is_hs: "str"
    act_name: "str"
    act_ent_type: "str"

    # stk_limits
    up_limit: "float64"
    down_limit: "float64"

    # limit_list_ths
    price: "float64"
    open_num: "int64"
    lu_desc: "str"
    limit_type: "str"
    tag: "str"
    status: "str"
    first_lu_time: "str"
    last_lu_time: "str"
    first_ld_time: "str"
    last_ld_time: "str"
    limit_order: "float64"
    limit_amount: "float64"
    turnover_rate: "float64"
    free_float: "float64"
    lu_limit_order: "float64"
    limit_up_suc_rate: "float64"
    turnover: "float64"
    rise_rate: "float64"
    sum_float: "float64"
    market_type: "str"

    # limit_list_d
    float_mv: "float64"
    total_mv: "float64"
    turnover_ratio: "float64"
    fd_amount: "float64"
    first_time: "str"
    last_time: "str"
    open_times: "int64"
    up_stat: "str"
    limit: "str"
    limit_times: "int64"
