tushare:
    token: "2876ea85cb005fb5fa17c809a98174f2d5aae8b1f830110a5ead6211"

api_profile:
    daily:
        expire_days: 1
    trade_cal:
        expire_days: 1
    stock_basic:
        expire_days: 1
    listed_shares:
        expire_days: 1
    stk_limits:
        expire_days: 1
    default:
        expire_days: 5

field_types:
    ts_code: "str"
    trade_date: "str"
    open: "float64"
    high: "float64"
    low: "float64"
    close: "float64"
    pre_close: "float64"
    change: "float64"
    pct_chg: "float64"
    vol: "float64"
    amount: "float64"
    exchange: "str"
    cal_date: "str"
    is_open: "str"
    pretrade_date: "str"
    symbol: "str"
    name: "str"
    area: "str"
    industry: "str"
    fullname: "str"
    enname: "str"
    cnspell: "str"
    market: "str"
    curr_type: "str"
    list_date: "str"
    delist_date: "str"
    list_status: "str"
    is_hs: "str"
    act_name: "str"
    act_ent_type: "str"
    up_limit: "float64"
    down_limit: "float64"
