tushare:
    token: "2876ea85cb005fb5fa17c809a98174f2d5aae8b1f830110a5ead6211"

api_profile:
    daily:
        expire_days: 1
    default:
        expire_days: 5

field_types:
    ts_code: "str"
    trade_date: "str"
    open: "float64"
    high: "float64"
    low: "float64"
    close: "float64"
    pre_close: "float64"
    change: "float64"
    pct_chg: "float64"
    vol: "float64"
    amount: "float64"
